spring:
  # profiles:
  config:
    activate:
      on-profile: dev

  # mariadb
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?${DB_OPTIONS}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

# mybatis
mybatis:
  mapper-locations: classpath:/mappers/**/*Mapper.xml
  config-location: classpath:/mappers/config/mybatis-config.xml
