spring:
  # profiles:
  config:
    activate:
      on-profile: dev

  # mariadb
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?${DB_OPTIONS}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

# mybatis
mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  config-location: classpath:/mybatis/mybatis-config.xml

# jwt
jwt:
  secret: 6OvJOWhmXqNQgR0KUJri8NRkIPWEMOz670ZOmfoD0zq
  access-token-expiration: 10800000 # 3시간 (ms)

youtube:
  api:
    key: AIzaSyCdhmTOK8hus6guX8kRuohzsR7c4Y7if-M
