spring:
  # profiles:
  config:
    activate:
      on-profile: dev

  # mariadb
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?${DB_OPTIONS}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

# mybatis
mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  config-location: classpath:/mybatis/mybatis-config.xml

# jwt
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 10800000 # 3시간 (ms)

youtube:
  api:
    key: ${YOUTUBE_API_KEY}
